-- AlterTable
ALTER TABLE "User" ADD COLUMN     "address" TEXT DEFAULT 'false',
ADD COLUMN     "country" TEXT DEFAULT 'false',
ADD COLUMN     "dateOfBirth" TEXT DEFAULT 'false',
ADD COLUMN     "favoriteSport" TEXT DEFAULT 'false',
ADD COLUMN     "gender" TEXT DEFAULT 'false',
ADD COLUMN     "hobbiesInterests" TEXT DEFAULT 'false',
ADD COLUMN     "maritalStatus" TEXT DEFAULT 'false',
ADD COLUMN     "postalCode" TEXT DEFAULT 'false',
ADD COLUMN     "preferredMovie" TEXT DEFAULT 'false',
ADD COLUMN     "preferredMusic" TEXT DEFAULT 'false',
ADD COLUMN     "spouseFirstName" TEXT DEFAULT 'false',
ADD COLUMN     "spouseLastName" TEXT DEFAULT 'false',
ADD COLUMN     "spouseSalutation" TEXT DEFAULT 'false',
ALTER COLUMN "firstName" DROP NOT NULL,
ALTER COLUMN "firstName" SET DEFAULT 'false',
ALTER COLUMN "lastName" DROP NOT NULL,
ALTER COLUMN "lastName" SET DEFAULT 'false',
ALTER COLUMN "salutation" DROP NOT NULL,
ALTER COLUMN "salutation" SET DEFAULT 'false';
